In [4]:
import torch
import numpy as np
import time

#use device for apple https://developer.apple.com/metal/pytorch/
#use device 2 for nvidia gpus
device = torch.device("mps") if torch.backends.mps.is_available() else 'cpu'
device2 = 'cuda' if torch.cuda.is_available() else 'cpu'
#device2 ='gpu' if torch.appl

print(device)
print(device2)

mps
cpu


In [5]:
probabilites  = torch.tensor([0.1,0.9]``)
samples = torch.multinomial(probabilites, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 0, 1, 1, 1, 1, 1, 1])


In [7]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])),dim=0)
print(out)

tensor([1, 2, 3, 4, 5])


In [8]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [9]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])